//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNO()
        {
            this.INCIDENCIA = new HashSet<INCIDENCIA>();
            this.MATRICULA = new HashSet<MATRICULA>();
        }
    
        public int dni_alu { get; set; }
        public string app_alu { get; set; }
        public string apm_alu { get; set; }
        public string nom_alu { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> edad { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<int> id_carrera { get; set; }
        public Nullable<int> id_distrito { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENCIA> INCIDENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
    }
}
