//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASE()
        {
            this.MATRICULA_CURSO_CLASE = new HashSet<MATRICULA_CURSO_CLASE>();
        }
    
        public int id_clase { get; set; }
        public string sesion { get; set; }
        public Nullable<int> id_sede { get; set; }
    
        public virtual SEDE SEDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA_CURSO_CLASE> MATRICULA_CURSO_CLASE { get; set; }
    }
}
