//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIA
    {
        public int id_incidencia { get; set; }
        public Nullable<bool> impacto { get; set; }
        public string impacto_desc { get; set; }
        public Nullable<int> dni_alu { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
