//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ISILNotasEntities : DbContext
    {
        public ISILNotasEntities()
            : base("name=ISILNotasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<CICLO> CICLO { get; set; }
        public virtual DbSet<CLASE> CLASE { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<INCIDENCIA> INCIDENCIA { get; set; }
        public virtual DbSet<MATRICULA> MATRICULA { get; set; }
        public virtual DbSet<MATRICULA_CURSO> MATRICULA_CURSO { get; set; }
        public virtual DbSet<MATRICULA_CURSO_CLASE> MATRICULA_CURSO_CLASE { get; set; }
        public virtual DbSet<NOTA> NOTA { get; set; }
        public virtual DbSet<PROFESOR> PROFESOR { get; set; }
        public virtual DbSet<PROFESOR_CURSO> PROFESOR_CURSO { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_NOTA> TIPO_NOTA { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_ActualizarAlumno(Nullable<int> dni_alu, string app_alu, string apm_alu, string nom_alu, string direccion, string telefono, string email, Nullable<int> edad, string nacionalidad, Nullable<int> id_carrera, Nullable<int> id_distrito)
        {
            var dni_aluParameter = dni_alu.HasValue ?
                new ObjectParameter("dni_alu", dni_alu) :
                new ObjectParameter("dni_alu", typeof(int));
    
            var app_aluParameter = app_alu != null ?
                new ObjectParameter("app_alu", app_alu) :
                new ObjectParameter("app_alu", typeof(string));
    
            var apm_aluParameter = apm_alu != null ?
                new ObjectParameter("apm_alu", apm_alu) :
                new ObjectParameter("apm_alu", typeof(string));
    
            var nom_aluParameter = nom_alu != null ?
                new ObjectParameter("nom_alu", nom_alu) :
                new ObjectParameter("nom_alu", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var nacionalidadParameter = nacionalidad != null ?
                new ObjectParameter("nacionalidad", nacionalidad) :
                new ObjectParameter("nacionalidad", typeof(string));
    
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAlumno", dni_aluParameter, app_aluParameter, apm_aluParameter, nom_aluParameter, direccionParameter, telefonoParameter, emailParameter, edadParameter, nacionalidadParameter, id_carreraParameter, id_distritoParameter);
        }
    
        public virtual int usp_ActualizarCurso(Nullable<int> id_curso, string nombre, Nullable<int> credito)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var creditoParameter = credito.HasValue ?
                new ObjectParameter("credito", credito) :
                new ObjectParameter("credito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCurso", id_cursoParameter, nombreParameter, creditoParameter);
        }
    
        public virtual int usp_ActualizarProfesor(Nullable<int> dni_pro, string app_pro, string apm_pro, string nom_pro, string direccion, string email, Nullable<int> id_distrito)
        {
            var dni_proParameter = dni_pro.HasValue ?
                new ObjectParameter("dni_pro", dni_pro) :
                new ObjectParameter("dni_pro", typeof(int));
    
            var app_proParameter = app_pro != null ?
                new ObjectParameter("app_pro", app_pro) :
                new ObjectParameter("app_pro", typeof(string));
    
            var apm_proParameter = apm_pro != null ?
                new ObjectParameter("apm_pro", apm_pro) :
                new ObjectParameter("apm_pro", typeof(string));
    
            var nom_proParameter = nom_pro != null ?
                new ObjectParameter("nom_pro", nom_pro) :
                new ObjectParameter("nom_pro", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarProfesor", dni_proParameter, app_proParameter, apm_proParameter, nom_proParameter, direccionParameter, emailParameter, id_distritoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarAlumno_Result> usp_ConsultarAlumno(Nullable<int> dni_alu)
        {
            var dni_aluParameter = dni_alu.HasValue ?
                new ObjectParameter("dni_alu", dni_alu) :
                new ObjectParameter("dni_alu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarAlumno_Result>("usp_ConsultarAlumno", dni_aluParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCarrera_Result> usp_ConsultarCarrera(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCarrera_Result>("usp_ConsultarCarrera", nombreParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCurso_Result> usp_ConsultarCurso(Nullable<int> id_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCurso_Result>("usp_ConsultarCurso", id_cursoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarDistrito_Result> usp_ConsultarDistrito(Nullable<int> id_distrito)
        {
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarDistrito_Result>("usp_ConsultarDistrito", id_distritoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarDistritoAlumno_Result> usp_ConsultarDistritoAlumno(Nullable<int> id_distrito)
        {
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarDistritoAlumno_Result>("usp_ConsultarDistritoAlumno", id_distritoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarNotasAlumno_Result> usp_ConsultarNotasAlumno(Nullable<int> dni_alu)
        {
            var dni_aluParameter = dni_alu.HasValue ?
                new ObjectParameter("dni_alu", dni_alu) :
                new ObjectParameter("dni_alu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarNotasAlumno_Result>("usp_ConsultarNotasAlumno", dni_aluParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarProfesor_Result> usp_ConsultarProfesor(Nullable<int> dni_pro)
        {
            var dni_proParameter = dni_pro.HasValue ?
                new ObjectParameter("dni_pro", dni_pro) :
                new ObjectParameter("dni_pro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarProfesor_Result>("usp_ConsultarProfesor", dni_proParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarSede_Result> usp_ConsultarSede(Nullable<int> id_sede)
        {
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarSede_Result>("usp_ConsultarSede", id_sedeParameter);
        }
    
        public virtual ObjectResult<usp_ListarAlumno_Result> usp_ListarAlumno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAlumno_Result>("usp_ListarAlumno");
        }
    
        public virtual ObjectResult<usp_ListarCarrera_Result> usp_ListarCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCarrera_Result>("usp_ListarCarrera");
        }
    
        public virtual ObjectResult<usp_ListarCurso_Result> usp_ListarCurso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCurso_Result>("usp_ListarCurso");
        }
    
        public virtual ObjectResult<usp_ListarDistrito_Result> usp_ListarDistrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarDistrito_Result>("usp_ListarDistrito");
        }
    
        public virtual ObjectResult<usp_ListarProfesor_Result> usp_ListarProfesor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarProfesor_Result>("usp_ListarProfesor");
        }
    
        public virtual ObjectResult<usp_ListarSede_Result> usp_ListarSede()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSede_Result>("usp_ListarSede");
        }
    }
}
