//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRICULA()
        {
            this.MATRICULA_CURSO = new HashSet<MATRICULA_CURSO>();
        }
    
        public int id_matricula { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> dni_alu { get; set; }
        public Nullable<int> id_ciclo { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual CICLO CICLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA_CURSO> MATRICULA_CURSO { get; set; }
    }
}
