//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRICULA_CURSO()
        {
            this.MATRICULA_CURSO_CLASE = new HashSet<MATRICULA_CURSO_CLASE>();
            this.NOTA = new HashSet<NOTA>();
        }
    
        public int id_matricula_curso { get; set; }
        public Nullable<int> id_matricula { get; set; }
        public Nullable<int> id_curso { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual MATRICULA MATRICULA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA_CURSO_CLASE> MATRICULA_CURSO_CLASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA> NOTA { get; set; }
    }
}
