//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA_CURSO_CLASE
    {
        public int id_matricula_curso_clase { get; set; }
        public Nullable<int> id_matricula_curso { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<bool> asistencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual CLASE CLASE { get; set; }
        public virtual MATRICULA_CURSO MATRICULA_CURSO { get; set; }
    }
}
