//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        public int id_nota { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<int> id_tipo_nota { get; set; }
        public Nullable<int> id_matricula_curso { get; set; }
    
        public virtual MATRICULA_CURSO MATRICULA_CURSO { get; set; }
        public virtual TIPO_NOTA TIPO_NOTA { get; set; }
    }
}
